### ISSUE TITLE
Update the LEAD mastertable

### ISSUE THREAD

**Issue by edambo** [brad-cannell/detect_fu_interviews_master_table#16]
# Overview

Quick description of what this task is...

# Tasks

- [x] Explain the assessment types and include other details about the data (include methods section from paper).
- [x] Explain the computation of the LEAD final determination (include methods section from paper).
- [x] Make separate tables for each abuse type.
- [x] Convert tables to flextables
- [x] Remove the "Count and Percentage of Dissenting Votes for Each Panelist Discipline" table
- [x]  Locate data for the initial MedStar visits
- [x] Create a confusion matrix with the initial MedStar visit data and the final determination data (counts as positive if at least one of the items in the DETECT tool was positive).
- [x] Update the confusion matrix
  - [x] Move to the top of the page - just after the methods
  - [x] Move column headers to the top of the confusion matrix
  - [x] Flip true positive and true negative so that positive is on the left.
  - [x] Add row and column totals
  - [x] Calculate sensitivity and specificity (and anything else that looks interesting to you).
- [x] Move "Final LEAD Panel Assessment Abuse Determination" to be directly under the "Unique Medstar ID Summary."
